Fix interactivity overloads
DSharpPlus/DSharpPlus pull request #1012
Opened 2021-07-31 15:50 UTC by VelvetThePanda

Fixes a Roslyn issue induced by the library because interactivity overloads were ambiguous

2021-07-31 15:52 UTC, IDoEverything commented on DSharpPlus.Interactivity/InteractivityExtension.cs
> -            DiscordChannel channel, DiscordUser user, IEnumerable<Page> pages, PaginationButtons buttons = null,
Should probably add in the documentation that setting it null uses the default buttons

2021-08-01 23:21 UTC, Neuheit requested changes
This is the wrong way to structure this. I would instead just make a 3rd overload of SendPaginatedMessageAsync that just takes the following parameters (no pagination buttons/emojis): 

```csharp
DiscordChannel channel, DiscordUser user, IEnumerable<Page> pages, PaginationBehaviour? behaviour = default, ButtonPaginationBehavior? deletion = default, CancellationToken? token = default
```

And then keep the other two overloads how they are, but make paginationbuttons/enojis a required parameter. Making the optional cancellation tokens mandatory is also not necessary.

2021-08-01 23:23 UTC, VelvetThePanda commented
> 3rd overload of SendPaginatedMessageAsync that just takes the following parameters (no pagination buttons/emojis):
That only worsens ambiguity, though?

2021-08-01 23:23 UTC, VelvetThePanda commented
> Making the optional cancellation tokens mandatory is also not necessary.

It is, because right now you get "Ambiguous method invocation" from Roslyn, and people have complained

2021-08-01 23:24 UTC, Neuheit commented
> 
> 
> > 3rd overload of SendPaginatedMessageAsync that just takes the following parameters (no pagination buttons/emojis):
> 
> That only worsens ambiguity, though?

No because the 4th parameter will be required for the other two.

2021-08-01 23:25 UTC, Neuheit commented
We want to have buttons to be preferred anyway so I would just construct that internally for the 3rd overload.

2021-08-01 23:26 UTC, VelvetThePanda commented
> > > 3rd overload of SendPaginatedMessageAsync that just takes the following parameters (no pagination buttons/emojis):
> > 
> > 
> > That only worsens ambiguity, though?
> 
> No because the 4th parameter will be required for the other two.

Sure, but what would the third overload even do?

2021-08-02 01:01 UTC, Neuheit commented
Like I said it just acts as a default method (and initializes a default paginationbuttons class internally).

2021-08-02 22:13 UTC, VelvetThePanda commented
> Like I said it just acts as a default method (and initializes a default paginationbuttons class internally).

I tried to copy paste, spent literally 25 minutes trying to figure out why it didn't work, and then got bamboozled by nullable value types

2021-08-03 12:43 UTC, IDoEverything approved these changes
LGTM

2021-08-03 19:56 UTC, Neuheit commented
It's better, but please make sure the cancellation tokens are not nullable. they should be optional and be set to default.

2021-08-03 19:57 UTC, VelvetThePanda commented
> It's better, but please make sure the cancellation tokens are not nullable. they should be optional and be set to default.

They...Are??

2021-08-03 19:58 UTC, VelvetThePanda commented
Oh wait I missed some

2021-08-04 01:23 UTC, Neuheit approved these changes

2021-08-04 01:23 UTC, merged