Fix editing messages containing replies in the message builder
DSharpPlus/DSharpPlus pull request #1059
Opened 2021-08-27 14:19 UTC by VelvetThePanda

Fix modifying messages throwing an exception when using the DiscordMessageBuilder

# Notes
I'm 99% sure I fixed this before

2021-09-03 03:34 UTC, Neuheit commented
If we're removing this we should probably add a disclaimer to the `WithReply()` method stating that they can't modify a reply.

2021-09-03 03:35 UTC, VelvetThePanda commented
Sounds good

On Thu, Sep 2, 2021 at 11:34 PM Neuheit ***@***.***> wrote:

> If we're removing this we should probably add a disclaimer to the
> WithReply() method stating that they can't modify a reply.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DSharpPlus/DSharpPlus/pull/1059#issuecomment-912228538>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKDY45XT2CED46Q2HWTV4QTUAA63NANCNFSM5C5UXO2Q>
> .
>

2021-09-05 18:08 UTC, VelvetThePanda commented
@Neuheit should be good, I think.

2021-09-05 18:14 UTC, Emzi0767 requested changes

2021-09-05 18:14 UTC, Emzi0767 commented on DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
>                  if (this.Files?.Count == 0 && string.IsNullOrEmpty(this.Content) && (!this.Embeds?.Any() ?? true) && this.Sticker is null)
If the surrounding scope bracket was remvoed, this should be unindented. Am I missing something?

2021-09-19 16:24 UTC, Emzi0767 approved these changes

2021-09-19 16:25 UTC, merged