Slash command localization support
DSharpPlus/DSharpPlus pull request #1225
Opened 2022-02-23 01:20 UTC by VelvetThePanda

Adds localization support to slash commands. This is currently under beta testing and I've yet to even test it myself.

2022-03-02 13:11 UTC, baruchvlz commented on DSharpPlus.SlashCommands/Localization.cs
> +        PeurtoRicoEnglish,
```suggestion
        PuertoRicoEnglish,
```

2022-03-25 20:02 UTC, kuylar requested changes

2022-03-25 20:16 UTC, VelvetThePanda commented on DSharpPlus.SlashCommands/Localization.cs
> +        PeurtoRicoEnglish,
Blame devsnek /ij

2022-03-25 20:17 UTC, VelvetThePanda commented
If it breaks we hard-boil the egg and send our sacrifice to Emzi.

2022-03-25 20:17 UTC, merged

2022-03-25 20:19 UTC, kuylar commented
I'm alright with that :v: