Update DiscordRestClient.cs
DSharpPlus/DSharpPlus pull request #1317
Opened 2022-05-21 17:15 UTC by InFTord

# Summary
Fixed another typo.
# Details
💀 

# Changes proposed
* Typo
* Is
* GONE
* 
# Notes
help

2022-05-21 17:15 UTC, InFTord commented
im your local typo fixer x3

2022-05-21 17:15 UTC, OoLunar commented
Please add subsequent typos in a singular PR, thank you.

2022-05-21 17:23 UTC, InFTord commented
question: should i change stuff like words being not caps sometimes? (like id in one part of docs, Id in second one, and ID in third one)

2022-05-21 17:26 UTC, OoLunar commented
If I say yes, how large do you plan on making this PR

2022-05-21 17:27 UTC, InFTord commented
Good question, it prob will one file (DiscordRestClient) for now

2022-05-21 17:30 UTC, OoLunar commented
Sounds good

2022-05-21 17:48 UTC, InFTord commented
imma  gonna recheck it next morning, cuz im really tired
but i finished the file!

2022-05-21 17:49 UTC, InFTord commented
as i said, editing DiscordRestClient with github editor is bad thing to do 😿

2022-05-21 19:54 UTC, ExaInsanity requested changes
I had no idea the xmldocs were this inconsistent with capitalization of abbreviations. Regardless:

2022-05-21 19:54 UTC, ExaInsanity commented on DSharpPlus.Rest/DiscordRestClient.cs
> +        /// <param name="overwrite_id">OverwriteIDid</param>
this doesn't seem right

2022-05-21 20:21 UTC, OoLunar commented on DSharpPlus.Rest/DiscordRestClient.cs
> +        /// <param name="overwrite_id">OverwriteIDid</param>
Failed sed moment

2022-05-22 06:53 UTC, InFTord commented on DSharpPlus.Rest/DiscordRestClient.cs
> +        /// <param name="overwrite_id">OverwriteIDid</param>
ok i failed, gonna fix it rn

2022-05-22 06:57 UTC, InFTord commented
![i forgot, that i also found some typos](https://user-images.githubusercontent.com/60395110/169682951-ed350299-d309-4062-8861-2225d5f2cde0.png)

2022-05-22 06:57 UTC, InFTord commented
found some typos yesterday (and forgot about them)

2022-05-22 07:00 UTC, InFTord commented
anyways, on my way to create a new PR with basically same thing, but different files (it prob gonna be bigger)

2022-05-22 10:59 UTC, ExaInsanity approved these changes

2022-05-22 14:09 UTC, InFTord commented
i regret adding lunar to review this PR :trollface:

2022-05-22 17:21 UTC, OoLunar commented
@InFTord, since this PR is just documentation with no code changes, I encourage you to add to this PR instead of creating new PR's per file. Thank you for understanding.

2022-05-22 17:23 UTC, OoLunar approved these changes

2022-05-23 07:20 UTC, InFTord commented
![undocumented stuff?](https://user-images.githubusercontent.com/60395110/169764993-f5f5fe66-6cdb-4550-970d-1ddb2d7ad96d.png)

2022-05-27 15:26 UTC, merged