feat: add IInteractionContextAccessor, for log enrichment
DSharpPlus/DSharpPlus pull request #1552
Opened 2023-05-10 10:57 UTC by raeyulca

# Summary
Adds an optionally-injected interface, `IInteractionContextAccessor`, for accessing the current `InteractionContext` outside of application commands and pre-execution checks.

# Details
This interface can be injected into a class that implements `Serilog.Core.ILogEventEnricher`.
This will allow enriching of logs with fields from the current `InteractionContext`.
To use, the `IInteractionContextAccessor` must be registered as a singleton.

An example enricher:
```c#
public class InteractionContextEnricher : ILogEventEnricher
{
    private IInteractionContextAccessor InteractionContextAccessor;
    public InteractionContextEnricher(IInteractionContextAccessor interactionContextAccessor)
    {
        IInteractionContextAccessor = interactionContextAccessor;
    }
    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
        if (InteractionContextAccessor.InteractionContext is null)
        {
            return;
        }
        var ctx = InteractionContextAccessor.InteractionContext;
        logEvent.AddPropertyIfAbsent(propertyFactory.CreateProperty("command", ctx.CommandName));
        logEvent.AddPropertyIfAbsent(propertyFactory.CreateProperty("channel_name", ctx.Channel.Name));
        
    }
}
```
And the result from a logged line:
![image](https://github.com/DSharpPlus/DSharpPlus/assets/56777335/fc741394-1aaf-4a5a-a96c-ca25531f2b0a)

# Changes proposed
- Add `IInteractionContextAccessor` and default implementation, `InteractionContextAccessor`

2023-05-10 12:55 UTC, akiraveliara requested changes
looks good to me, please document the new API though

2023-05-10 12:55 UTC, akiraveliara commented on DSharpPlus.SlashCommands/IInteractionContextAccessor.cs
> +    public InteractionContext? InteractionContext
documentation

2023-05-14 16:35 UTC, OoLunar requested changes
LGTM, I'm just being nitpicky

2023-05-14 16:35 UTC, OoLunar commented on DSharpPlus.SlashCommands/IInteractionContextAccessor.cs
> +
Redundant newline

2023-05-14 16:35 UTC, OoLunar commented on DSharpPlus.SlashCommands/SlashCommandsExtension.cs
> +
x2

2024-02-08 06:35 UTC, OoLunar commented
Closing as stale.

2024-02-08 06:35 UTC, closed without merging