clean up automod entities
DSharpPlus/DSharpPlus pull request #1608
Opened 2023-08-26 18:45 UTC by InFTord

Make sure you familiarize yourself with our contributing guidelines.

# Summary
A lot of PRs like this will appear in next days. Basically cleaning up and modernizing the code. Not a lot going in automod, however. In theory, the biggest changes will be with DiscordGuild and DiscordChannel entities, but we'll see about that.

# Notes
Any additional notes go here.

2023-08-26 18:47 UTC, akiraveliara requested changes
this doesn't work; and also, i'd appreciate if you could nullable annotate the entity properties. just annotating every reference type is probably the best course of action since we don't want to break anything, cc @VelvetToroyashi

2023-08-26 18:47 UTC, akiraveliara commented on DSharpPlus/Entities/AutoModeration/Action/DiscordAutoModerationAction.cs
> +using Enums;
i'm sorry, no.

2023-08-26 18:47 UTC, akiraveliara commented on DSharpPlus/Entities/AutoModeration/Action/DiscordAutoModerationActionExecution.cs
> +using Enums;
here too

2023-08-26 18:55 UTC, InFTord commented
i feel myself stupid, but what do you mean exactly by nullable annotate the entity properties?

2023-08-27 01:36 UTC, OoLunar commented
`DiscordMessage message = null` -> `DiscordMessage? message = null`

2023-09-23 15:51 UTC, akiraveliara approved these changes

2023-09-23 15:52 UTC, merged