rename a bunch of things from slash- to interaction-
DSharpPlus/DSharpPlus pull request #1750
Opened 2024-02-06 19:38 UTC by akiraveliara

as discussed in https://canary.discord.com/channels/379378609942560770/1202000142170062928/1204476616051269682

2024-02-07 05:47 UTC, OoLunar requested changes
Food for thought

2024-02-07 05:47 UTC, OoLunar commented on DSharpPlus.Commands/Processors/SlashCommands/Attributes/InteractionAutoCompleteProviderAttribute.cs
> +public class InteractionAutoCompleteProviderAttribute(Type autoCompleteType) : Attribute
Autocomplete is currently only available for slash commands. Should remain as `SlashAutoCompleteProviderAttribute` imo.

2024-02-07 05:47 UTC, OoLunar commented on DSharpPlus.Commands/Processors/SlashCommands/Attributes/InteractionChannelTypesAttribute.cs
> +public sealed class InteractionChannelTypesAttribute(params ChannelType[] channelTypes) : Attribute
As above

2024-02-07 05:47 UTC, OoLunar commented on DSharpPlus.Commands/Processors/SlashCommands/Attributes/InteractionChoiceProviderAttribute.cs
> +public class InteractionChoiceProviderAttribute(Type providerType) : Attribute
As above

2024-02-07 05:47 UTC, OoLunar commented on DSharpPlus.Commands/Processors/SlashCommands/Attributes/InteractionMinMaxAttribute.cs
As above

2024-02-07 05:47 UTC, OoLunar commented on DSharpPlus.Commands/Processors/SlashCommands/Attributes/InteractionMinMaxLengthAttribute.cs
> +public sealed class InteractionMinMaxLengthAttribute : Attribute
As above

2024-02-07 21:04 UTC, Plerx2493 approved these changes
LGTM, if lunars requests getting applied

2024-02-12 21:09 UTC, OoLunar approved these changes

2024-02-12 21:09 UTC, merged