Implement Dispose pattern
DSharpPlus/DSharpPlus pull request #1762
Opened 2024-02-13 06:31 UTC by OoLunar

# Summary
The extension now properly supports the dispose pattern by clearing any properties and unregistering all events.

# Notes
I'm not actually sure if I implemented the dispose pattern in the same way that the BCL does.

2024-02-14 12:51 UTC, akiraveliara requested changes
you know what i think about your formatting, but...

2024-02-14 12:51 UTC, akiraveliara commented on DSharpPlus.Commands/CommandsExtension.cs
> +        return processor.ConfigureAsync(this);
this ruins the async stacktrace, let's not

2024-03-08 01:45 UTC, OoLunar commented on DSharpPlus.Commands/CommandsExtension.cs
> +        this._checks.Clear();
Readonly fields + `[]` might create a new instance.

2024-03-08 01:45 UTC, OoLunar commented on .editorconfig
> +csharp_style_prefer_primary_constructors = false:silent
I think so

2024-03-08 02:25 UTC, Plerx2493 approved these changes
LTGM

2024-03-08 02:25 UTC, Plerx2493 commented on .editorconfig
> +csharp_style_prefer_primary_constructors = false:silent
not really but i think we three agreed to it

2024-03-16 16:38 UTC, closed without merging