Split Default Command Handler Logic
DSharpPlus/DSharpPlus pull request #1819
Opened 2024-03-31 21:40 UTC by OoLunar

# Summary
This separates the internal logic of the default command handler from a single large method into several smaller methods. The intent is to allow other classes to inherit the default command handler and to easily be able to make minor changes while still be able to keep the default command execution behavior with relative ease.

# Changes
- Rename `CommandExecutor` to `DefaultCommandExecutor`
- Exposed all properties and methods to inheriting classes (`protected`)
- Deeply documented each split method
- Add `ContextCheckFailedData` for failed checks
- Documents the command wrapper IL generator utility files

# Notes
Tested.

2024-03-31 22:03 UTC, akiraveliara requested changes

2024-03-31 22:03 UTC, akiraveliara commented on DSharpPlus.Commands/Invocation/CommandEmitUtil.cs
> +        // Unless if it was done through context checks... Hm.
we shouldn't encourage misuse of context checks in the name of an already immensely questionable code pattern, ideally

2024-03-31 22:03 UTC, akiraveliara commented on DSharpPlus.Commands/Invocation/CommandEmitUtil.cs
> +        // We're going to take the slow path here and simply do `MethodInfo.Invoke`, for lack of a better way.
if there's no faster way it's not a slow path :when:

2024-03-31 22:03 UTC, akiraveliara commented on DSharpPlus.Commands/Invocation/CommandEmitUtil.cs
> +            dynamicMethodIlGenerator.Emit(OpCodes.Ldelem_Ref);
if you insist on copying the instruction documentation, at least use the proper names - `ldarg.1`, `ldc.i4`, `ldelem.ref` - this goes for the entire file

2024-03-31 22:03 UTC, akiraveliara commented on DSharpPlus.Commands/Invocation/CommandEmitUtil.cs
> +                // Change the handling behavior (unbox) of the instance (this) from a reference type to a value type.
i have no idea what this comment is supposed to mean.

2024-03-31 22:03 UTC, akiraveliara commented on DSharpPlus.Commands/Invocation/CommandEmitUtil.cs
>              if (method.DeclaringType!.IsValueType)
removing newlines added for logical separation of logically distinct code is generally ill-advisable

2024-03-31 22:45 UTC, OoLunar commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +    }
What guarantee

2024-03-31 22:47 UTC, OoLunar commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +    public virtual async ValueTask<(object? CommandObject, Exception? Error)> UnconditionallyExecuteAsync(CommandContext context)
Right but will anyone really want to make a shim of this class just to access one method? It feels like more hassle than it's worth. More often than not, it's just gonna be used for a `sudo` command

2024-03-31 22:47 UTC, akiraveliara commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +    }
not pooling instances

2024-03-31 22:49 UTC, OoLunar commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +            if (!context.Command.Method!.DeclaringType!.IsAbstract || !context.Command.Method.DeclaringType.IsSealed)
https://stackoverflow.com/a/1175901/10942966
> `static` classes are declared `abstract` and `sealed` at the IL level. So, you can check `IsAbstract` property to handle both `abstract` classes and `static` classes in one go (for your use case).

However, `abstract` classes are not the only types you can't instantiate directly. You should check for things like interfaces ([without the CoClass attribute](https://stackoverflow.com/questions/1093536/how-does-the-c-compiler-detect-com-types)) and types that don't have a constructor accessible by the calling code.

2024-03-31 22:49 UTC, OoLunar commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +    protected virtual async ValueTask<IReadOnlyList<ContextCheckFailedData>> ExecuteContextChecksAsync(CommandContext context)
What are those

2024-03-31 22:50 UTC, akiraveliara commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +            if (!context.Command.Method!.DeclaringType!.IsAbstract || !context.Command.Method.DeclaringType.IsSealed)
IsAbstract and IsSealed are very, very different things

2024-03-31 22:50 UTC, OoLunar commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +        // If there are no checks, we can skip this step.
Previously unreported bug, thanks for catching it

2024-03-31 22:50 UTC, OoLunar commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +            if (!context.Command.Method!.DeclaringType!.IsAbstract || !context.Command.Method.DeclaringType.IsSealed)
Yes they are. However that is how C# chooses to represent static classes

2024-03-31 22:52 UTC, akiraveliara commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +            if (!context.Command.Method!.DeclaringType!.IsAbstract || !context.Command.Method.DeclaringType.IsSealed)
this condition will prevent creating an instance of `sealed class Class`, so...

2024-03-31 22:54 UTC, OoLunar commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +            if (!context.Command.Method!.DeclaringType!.IsAbstract || !context.Command.Method.DeclaringType.IsSealed)
Live testing shows otherwise... Are we sure?

2024-03-31 23:01 UTC, akiraveliara commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +            if (!context.Command.Method!.DeclaringType!.IsAbstract || !context.Command.Method.DeclaringType.IsSealed)
no, actually

2024-04-03 22:42 UTC, akiraveliara approved these changes

2024-04-03 22:59 UTC, VelvetToroyashi approved these changes
Skimming, as to avoid making comments on framework architecture, so at a glance, looks fine

2024-04-03 23:00 UTC, merged