[Commands] Add the possibility to register commands to specific guilds
DSharpPlus/DSharpPlus pull request #1854
Opened 2024-04-22 22:17 UTC by Lounek09

Implement #1734 by adding overwrite method for all the `CommandExtension.AddCommand` and `CommandExtension.AddCommands` like DSP.SlashCommands does with `SlashCommandsExtension.RegisterCommands`

2024-04-22 22:25 UTC, Plerx2493 reviewed
Generall LGTM, some minor comments

2024-04-22 22:25 UTC, Plerx2493 commented on DSharpPlus.Commands/DefaultCommandExecutor.cs
> +namespace DSharpPlus.Commands;
Namespace blow usings please

2024-04-22 22:25 UTC, Plerx2493 commented on DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
>  using DSharpPlus.EventArgs;
nit: old stlye with linebreaks prefered, atleast personally

2024-04-22 22:26 UTC, OoLunar requested changes
Could we also do a `RequireGuildIdCheckAttribute`?

2024-04-22 22:36 UTC, akiraveliara commented
wrt RequireGuildIdCheck: users can just register commands to specifically that guild, no

2024-04-22 22:40 UTC, Plerx2493 commented
Question, how are we handling 2 Commands with the same name but other guilds? e.g. a `/rule` command could have different implementations for different guilds

2024-04-22 22:41 UTC, OoLunar commented
> wrt RequireGuildIdCheck: users can just register commands to specifically that guild, no

They could but I personally register all my commands by passing the assembly. I'd rather use attributes instead of filtering out the types that need to be registered to specific guilds.

2024-04-22 22:43 UTC, akiraveliara commented
i have opinions on encouraging such a pattern, but at the very least it's not a check then but registration metadata

2024-04-22 22:46 UTC, Lounek09 commented on DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
> +            discordCommands.AddRange(await extension.Client.BulkOverwriteGuildApplicationCommandsAsync(extension.DebugGuildId, guildsApplicationCommands.SelectMany(x => x.Value)));
I don't understand, this doesn't compile 😭

2024-04-23 04:09 UTC, OoLunar commented on DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
> +            discordCommands.AddRange(await extension.Client.BulkOverwriteGuildApplicationCommandsAsync(extension.DebugGuildId, guildsApplicationCommands.SelectMany(x => x.Value)));
Yeah I was in the wrong here. Carry on lol

2024-04-23 10:54 UTC, Lounek09 commented
> Could we also do a `RequireGuildIdCheckAttribute`?

done !

2024-04-23 14:31 UTC, akiraveliara reviewed
consider embedding the guild ids in upload metadata rather than a check, that way they aren't at all visible if the check would fail

2024-04-23 16:50 UTC, Lounek09 commented
> consider embedding the guild ids in upload metadata rather than a check, that way they aren't at all visible if the check would fail

Yeah, that's better you're right (and it's done🫣)

2024-04-23 16:55 UTC, akiraveliara approved these changes

2024-04-28 05:08 UTC, OoLunar requested changes

2024-04-28 05:08 UTC, OoLunar commented on DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
> +                .Select(x => x.First())));
What's this LINQ query for? Could we add a code comment for this?

2024-04-28 05:08 UTC, OoLunar commented on DSharpPlus.Commands/RegisterToGuildsAttribute.cs
> +
Double newline

2024-04-28 05:08 UTC, OoLunar commented on DSharpPlus.Commands/RegisterToGuildsAttribute.cs
> +
Trailing newline

2024-04-30 14:13 UTC, OoLunar approved these changes
LGTM. Tested?

2024-04-30 14:14 UTC, OoLunar commented
Oh, does it work for text commands too?

2024-04-30 14:14 UTC, akiraveliara commented
they mentioned running this a few times, so

2024-04-30 15:53 UTC, Lounek09 commented
> LGTM. Tested?

Yup, I run it in production right now, that's how I found the last bug 😅

> Oh, does it work for text commands too?

See this change : https://github.com/DSharpPlus/DSharpPlus/pull/1854/files#diff-89f69a773b7a1cf1cd35141ebb4b1affe6273067dfb3ad40a0119a54b8b9e75c

2024-04-30 15:54 UTC, merged