Provide documentation for `DSharpPlus.Commands`
DSharpPlus/DSharpPlus pull request #1867
Opened 2024-05-01 00:54 UTC by OoLunar

# Summary
Provides articles and documentation for the `DSharpPlus.Commands` package. Additionally obsoletes both the `DSharpPlus.CommandsNext` and the `DSharpPlus.SlashCommands` packages.

# Notes
Untested.

2024-05-01 06:33 UTC, Plerx2493 approved these changes
Some notes, otherwise looks good. Thank you for taking the time to write this all

2024-05-01 06:33 UTC, Plerx2493 commented on docs/articles/commands/processors/slash_commands/choice_provider_vs_autocomplete.md
> +## Implementing a Choice Provider
Maybe add information about DI for both implementations (injecting through ctor(?) and are they singletons?)

2024-05-01 06:33 UTC, Plerx2493 commented on docs/articles/commands/custom_argument_converters.md
> +# Custom Argument Converters
Here also: Do we provide DI for those?

2024-05-01 06:33 UTC, Plerx2493 commented on docs/faq.md
> +[5]: xref:articles.commands_next.dependency_injection
I think here was smth messed up

2024-05-01 11:09 UTC, akiraveliara commented
where did my section on parameter checks go :c

2024-05-01 11:11 UTC, akiraveliara requested changes

2024-05-01 11:11 UTC, akiraveliara commented on DSharpPlus.CommandsNext/CommandsNextExtension.cs
> +[Obsolete("DSharpPlus.CommandsNext is obsolete. Please consider using the new DSharpPlus.Commands extension instead.")]
CommandsNext isn't fully replaceable yet, for lack of help and overloads

2024-05-02 18:06 UTC, akiraveliara requested changes

2024-05-02 18:06 UTC, akiraveliara commented on DSharpPlus.CommandsNext/ExtensionMethods.cs
> +    [Obsolete("DSharpPlus.CommandsNext is obsolete. Please consider using the new DSharpPlus.Commands extension instead.")]
remove obsoletion here too

2024-05-02 19:29 UTC, akiraveliara approved these changes

2024-05-02 19:37 UTC, merged