fixes a bug where an empty parameter list would not cause a command to execute with default values
DSharpPlus/DSharpPlus pull request #1878
Opened 2024-05-05 20:07 UTC by akiraveliara

this, notably, does not address #1864/#1843, which hit when some but not all parameters are supplied

2024-05-05 20:20 UTC, VelvetToroyashi approved these changes

2024-05-05 20:33 UTC, OoLunar requested changes

2024-05-05 20:33 UTC, OoLunar commented on DSharpPlus.Commands/Processors/BaseCommandProcessor/BaseCommandProcessor.cs
> +                        parameter.DefaultValue.HasValue ? parameter.DefaultValue.Value : null
This should check that all parameters are optional instead of passing `null` for required parameters.

2024-05-05 20:33 UTC, OoLunar commented on DSharpPlus/Entities/Interaction/DiscordInteractionDataOption.cs
> +                DiscordApplicationCommandOptionType.Boolean => bool.Parse(this.RawValue),
```suggestion
            return this.Type switch
            {
                _ when this.RawValue is null => null,
                DiscordApplicationCommandOptionType.Boolean => bool.Parse(this.RawValue),
```

2024-05-05 20:33 UTC, OoLunar commented on DSharpPlus/Entities/Interaction/DiscordInteractionDataOption.cs
> +#pragma warning disable IDE0046
Try to use `SuppressMessage` when possible

2024-05-06 16:02 UTC, OoLunar commented on DSharpPlus.Commands/Processors/BaseCommandProcessor/BaseCommandProcessor.cs
> +                            Exception = new ArgumentParseException(converterContext.Parameter, null, $"Argument Converter for type {converterContext.Parameter.Type.FullName} was unable to parse the a
> $"Argument Converter for type {converterContext.Parameter.Type.FullName} was unable to parse the argument."

Try to give the most amount of information possible to the dev. The dev is already receiving a `ArgumentParseException`, it's pretty clear that the argument parser was unable to parse the argument. What about:

> $"Not enough argument data to parse {converterContext.Parameter.Name}"

2024-05-07 05:36 UTC, OoLunar approved these changes

2024-05-07 05:36 UTC, merged