feat(interactivity): Add support for components in pages
DSharpPlus/DSharpPlus pull request #1967
Opened 2024-06-18 08:07 UTC by VelvetToroyashi

Closes #1966

2024-06-18 10:56 UTC, akiraveliara commented on DSharpPlus.Interactivity/InteractivityExtension.cs
> +        PaginationButtons bts = buttons         ?? this.Config.PaginationButtons;
naming, whitespace style

2024-06-18 10:56 UTC, akiraveliara commented on DSharpPlus.Interactivity/InteractivityExtension.cs
> +        bts = new(bts);
why?

2024-06-18 10:57 UTC, VelvetToroyashi commented on DSharpPlus.Interactivity/InteractivityExtension.cs
> +        PaginationButtons bts = buttons         ?? this.Config.PaginationButtons;
c&p

2024-06-25 00:41 UTC, Plerx2493 requested changes

2024-06-25 00:41 UTC, Plerx2493 commented on DSharpPlus.Interactivity/EventHandling/Requests/PaginationEmojis.cs
> +    : this(builder.Content, builder.Embeds.FirstOrDefault(), builder.Components) { }
This should also be yeeted

2024-06-25 01:56 UTC, Plerx2493 approved these changes

2024-06-27 11:59 UTC, merged