Improve the VoiceNext queue
DSharpPlus/DSharpPlus pull request #566
Opened 2020-05-04 16:54 UTC by WamWooWam

# Summary
Fixes #537 by limiting the size of the VoiceNext packet queue, and modify the queue to store PCM instead of encoded Opus.

# Details
I've switched out the `ConcurrentQueue` for a `BlockingCollection` (which uses `ConcurrentQueue` under the hood) to limit number of packets that can be in the queue at any one time, defaulting to 25 packets or about 500ms of audio. This means that you have control over the buffer within VoiceNext, and also means that when you stop writing data to the `VoiceTransmitStream`, the audio will actually stop on Discord's end too.

I also made the queue store PCM audio, instead of compressed Opus, which potentially fixes some threading issues (OpusEncoders aren't thread safe) and also spreads out the CPU load of encoding packets to the time they're actually sent. And let's be real, if you can't encode 20ms of Opus audio in under 20ms, something's gone wrong.

Oh I also fixed UdpPing, because it would always return zero.

# Changes proposed
* Limit the size of the VoiceNext queue
* Make the VoiceNext queue store PCM data.
* Fix the test bot, because capturing stderr then not reading it causes ffmpeg to get quite sad
* Fix the `UdpPing` property on `VoiceNextConnection` always returning 0.
* Repeat myself adnauseam.

2020-05-04 16:57 UTC, Giggitybyte commented
Based Wam

2020-05-04 18:51 UTC, Emzi0767 commented
If you're limiting queue size, why not use a bounded channel instead? It's async, so won't be stalling tasks.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
From: Luke Triano <notifications@github.com>
Sent: Monday, May 4, 2020 6:57:42 PM
To: DSharpPlus/DSharpPlus <DSharpPlus@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [DSharpPlus/DSharpPlus] Improve the VoiceNext queue (#566)


Based Wam

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/DSharpPlus/DSharpPlus/pull/566#issuecomment-623582561>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAF7QQGBDY6FGDLQ2ZS4A73RP3XYNANCNFSM4MY5I6AA>.

2020-05-04 18:57 UTC, WamWooWam commented
would System.Threading.Channels not be another dependency and that's bad?

2020-05-04 19:04 UTC, Emzi0767 commented
Meh. We can afford it.

2020-05-04 19:10 UTC, WamWooWam commented
The problem with this is that you could then only write to the stream asynchronously, while as it stands all the code we have depends on synchronous writing, on top of that we're already blocking on tasks no matter what we really do because of the way the send buffer works

2020-05-04 19:15 UTC, Emzi0767 commented
Are you sure about that?

![NuGet says otherwise](https://totally-not.a-sketchy.site/4Q8R65e.png)

2020-05-04 19:19 UTC, WamWooWam commented
More, since when have we been able to override `Stream#WriteAsync`

2020-08-28 00:42 UTC, Emzi0767 requested changes

2020-08-28 00:42 UTC, Emzi0767 commented on DSharpPlus.VoiceNext/VoiceNextConnection.cs
> +                if (hasPacket) {
Brace style.

2020-08-28 00:43 UTC, Emzi0767 commented
So thing with BlockingCollection is... the fact that it blocks. And that stalls tasks. And that starves the scheduler's pool. This is why I'd prefer an async-based (e.g. Channels) solution.

2020-11-14 14:18 UTC, WamWooWam commented
As per discussion [in the Discord](https://discord.com/channels/379378609942560770/379386901725052928/777152309901262859), I've refactored `VoiceTransmitStream` to no longer be a subclass of `System.IO.Stream` because it doesn't provide a good interface for async-only IO.

`VoiceTransmitStream` has been renamed to `VoiceTransmitSink` to avoid confusion, all Read/Seek/Length methods have been removed and an extension method has been provided to make copying from `IO.Stream`s as simple as possible.

2020-11-14 14:21 UTC, Emzi0767 commented
It seems the natives were committed?

2020-11-14 14:32 UTC, Emzi0767 approved these changes

2020-11-14 14:50 UTC, WamWooWam commented
This also should close #481, because any functionality that PR could provide this one provides implicitly

2020-11-14 15:03 UTC, merged