Fix stickers
DSharpPlus/DSharpPlus pull request #705
Opened 2020-12-04 23:06 UTC by WamWooWam

# Summary
Fixes an issue where stickers wouldn't deserialise correctly.

# Details
The [documentation for stickers](https://discord.com/developers/docs/resources/channel#message-object-message-sticker-structure) says that `tags` is a comma separated list not an array, so I've modified the class store the string internally and provide a split list.

Also made some property setters which should've been `internal`, `internal`,

2020-12-04 23:43 UTC, Giggitybyte commented
lmao @ branch name

2020-12-05 00:18 UTC, Neuheit commented on DSharpPlus/Entities/DiscordMessageSticker.cs
> +        public string[] Tags => _internalTags.Split(',');
```suggestion
        public string[] Tags => this._internalTags.Split(',');
```

2020-12-05 01:18 UTC, Neuheit approved these changes
no pls

2020-12-08 16:52 UTC, Emzi0767 requested changes

2020-12-08 16:52 UTC, Emzi0767 commented on DSharpPlus/Entities/DiscordMessageSticker.cs
> +        public string[] Tags => this._internalTags.Split(',');
Might be a good idea to tag with `[JsonIgnore]` should sending ever came to be for whatever reason.

2020-12-19 01:19 UTC, Emzi0767 approved these changes

2020-12-19 01:19 UTC, merged