Updates permissions to include Use Slash Commands
DSharpPlus/DSharpPlus pull request #849
Opened 2021-04-21 17:26 UTC by Soyvolon

# Summary
Implements the Use Slash Commands permission to `DSharpPlus.Permissions`

# Details
Adds the permission `UseSlashCommands` to the `Permissions` enum.

# Changes proposed
* Add `Permissions.UseSlashCommands` with a value of `0x0000000080000000`
* Modify the `FULL_PERMS` and `All` values to the result of the old `All` value and the value of `UseSlashCommands`

2021-04-23 11:17 UTC, Lulalaby commented
What about adding the permission `REQUEST_TO_SPEAK` too?

2021-04-23 12:00 UTC, Lulalaby requested changes
Update with permission `REQUEST_TO_SPEAK`

2021-04-23 12:00 UTC, Lulalaby commented on DSharpPlus/Enums/Permission.cs
> +        All = 4294967295,
```suggestion
        All = 6441926655,
```

Thing here is, i tried to calculate the perms together.
the old perms, the new perms and the one i add are all different from yours. could it be that i msised something?
please correct if wrong.

2021-04-23 12:06 UTC, Emzi0767 commented
The scope of the PR, as per the title, is slash commands perm.

2021-04-23 12:08 UTC, Lulalaby requested changes

2021-04-23 12:08 UTC, Lulalaby commented on DSharpPlus/Enums/Permission.cs
> +        internal static Permissions FULL_PERMS { get; } = (Permissions)4294967295L;
```suggestion
        internal static Permissions FULL_PERMS { get; } = (Permissions)6441926655L;
```

2021-04-23 12:09 UTC, Lulalaby commented
> 
> 
> The scope of the PR, as per the title, is slash commands perm.

But since it's not merged yet I thought, it could be added too.

But ok.

But could someone please explain me how the all perms is calculated (for future then)

2021-04-23 13:38 UTC, Soyvolon commented
> But could someone please explain me how the all perms is calculated (for future then)

Permissions are calculated with [bitwise operations](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators), So getting the new full value would be `long newAll = (long)(Permissions.All | Permissions.NewPermission)`

2021-04-25 00:27 UTC, Lulalaby commented
> 
> 
> > But could someone please explain me how the all perms is calculated (for future then)
> 
> Permissions are calculated with [bitwise operations](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators), So getting the new full value would be `long newAll = (long)(Permissions.All | Permissions.NewPermission)`

Ah thank you!

2021-04-26 00:23 UTC, Neuheit approved these changes

2021-04-26 00:23 UTC, merged