Nsfw guilds
DSharpPlus/DSharpPlus pull request #850
Opened 2021-04-22 10:10 UTC by IDoEverything

# Summary
Adds the `nsfw` property to guilds

2021-04-23 06:59 UTC, Naamloos approved these changes
LGTM

2021-04-23 07:00 UTC, uwx requested changes

2021-04-23 07:00 UTC, uwx commented on DSharpPlus/Entities/Guild/DiscordGuild.cs
> +        public bool Nsfw { get; internal set; }
Property name should be `IsNsfw` to match other boolean properties

2021-04-23 07:01 UTC, uwx commented on DSharpPlus/Entities/Guild/DiscordGuild.cs
> +        public bool Nsfw { get; internal set; }
Actually, `IsNSFW`, that's what it is for channels.

2021-04-23 07:05 UTC, uwx approved these changes

2021-04-26 00:24 UTC, Neuheit commented on DSharpPlus/Entities/Guild/DiscordGuild.cs
> +        /// Gets whether this guild is designated as nsfw.
```suggestion
        /// Gets whether this guild is designated as NSFW.
```

2021-04-26 00:25 UTC, Neuheit approved these changes

2021-04-26 00:30 UTC, merged