Implement Stage Channels
DSharpPlus/DSharpPlus pull request #859
Opened 2021-04-25 13:11 UTC by IDoEverything

# Summary
Adds stage channels.

# Details
Added the stage channel type and the endpoints for updating voice state. I added stage channels wherever it checks for voice channels too, but I might have missed some, please let me know if this is the case. I didn't add the request to speak permission since there's already a pr for that.

# Changes proposed
* Add channel type 13
* Add update user voice state endpoints
* Add `request_to_speak_timestamp` property
* Update voice channel checks to include stage channels

2021-04-25 20:55 UTC, uwx requested changes

2021-04-25 20:55 UTC, uwx commented on DSharpPlus.Lavalink/LavalinkNodeConnection.cs
> +            if (channel.Guild == null || channel.Type != ChannelType.Voice || channel.Type != ChannelType.Stage)
This will not work.

2021-04-25 20:55 UTC, uwx commented on DSharpPlus/Entities/Channel/DiscordChannel.cs
> +
This could probably do with better documentation.

2021-04-25 20:55 UTC, uwx commented on DSharpPlus/Entities/Guild/DiscordMember.cs
> +
Better documentation here too.

2021-04-25 20:55 UTC, uwx commented on DSharpPlus/Entities/Voice/DiscordVoiceState.cs
> +
It should be possible to do this using JSON.NET's DateTimeOffset parsing.

2021-04-27 01:04 UTC, uwx approved these changes
LGTM

2021-04-27 05:25 UTC, Neuheit approved these changes

2021-04-27 05:25 UTC, merged