Fix webhook builder buttons
DSharpPlus/DSharpPlus pull request #915
Opened 2021-06-03 13:10 UTC by IDoEverything

# Summary
Fixes webhook builder not havng `AddComponents`

# Details
Added `AddComponents` to the webhook builder and fixed some small inconsistencies and unnecessary casts.

# Notes
Velvet bad

2021-06-03 13:19 UTC, VelvetThePanda commented
Cabbage you're a cabbage

2021-06-03 13:19 UTC, VelvetThePanda commented
That cast *is* neccessary

2021-06-03 13:21 UTC, VelvetThePanda requested changes

2021-06-03 13:21 UTC, VelvetThePanda commented on DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
> +            => this.AddComponents(components);
This is recursive now, and will cause a stack overflow, since this is the only overload that takes an array.

2021-06-04 02:20 UTC, Neuheit approved these changes

2021-06-04 02:20 UTC, merged