Add type converter for DiscordComponent
DSharpPlus/DSharpPlus pull request #924
Opened 2021-06-13 03:43 UTC by VelvetThePanda

# Summary
Fixes an issue where type information is lost in `DiscordMessage#Components` because the serializer doesn't handle inheritence.

# Details
Added a type converter for the current component types. 

## Old behavior:
![](https://cdn.velvetthepanda.dev/Y26GN.png) 
## Fixed behavior:
![](https://cdn.velvetthepanda.dev/V3bVs.png)

# Changes proposed
Deserializes components to their proper types when receiving messages from gateway/REST

# Notes
I did a good for once :)

2021-06-13 03:44 UTC, VelvetThePanda commented
>Failed build
>It works on my machine

2021-06-13 16:20 UTC, Emzi0767 requested changes
Why no separate file tho

2021-06-13 16:22 UTC, VelvetThePanda commented
> Why no separate file tho

It was initially like this, but then I looked at how some of the other converters worked and they were nested. I can change this though if you want.

2021-06-14 06:46 UTC, Emzi0767 approved these changes

2021-06-14 06:46 UTC, merged