Add TimeStamp support.
DSharpPlus/DSharpPlus pull request #940
Opened 2021-06-18 03:31 UTC by VelvetThePanda

# Summary
Adds support for timestamps, documented in discord/discord-api-docs#3135.

2021-06-18 03:33 UTC, IDoEverything commented
Shouldn't there be support for all the flags?

2021-06-18 03:43 UTC, VelvetThePanda commented
*Technically* speaking, yes, but:
1: that would require adding an enum, I suppose
2: Embed timestamps also use relative, which imo is the most useful

~~3: Since you're here anyway do you mind triaging this.~~

2021-06-18 03:45 UTC, IDoEverything commented
Doesn't really make sense to restrict it to only the relative one. Nothing wrong with an enum either

2021-06-18 03:54 UTC, VelvetThePanda commented
@IDoEverything done.

2021-06-18 03:57 UTC, IDoEverything approved these changes

2021-06-18 22:41 UTC, Emzi0767 commented on DSharpPlus/Enums/TimestampFormat.cs
> +    public enum TimestampFormat
`: char`?

2021-06-18 22:43 UTC, Emzi0767 commented on DSharpPlus/Formatter.cs
> +        public static string TimeStamp(TimeSpan time, TimestampFormat format = TimestampFormat.RelativeTime)
`s/S/s/`

2021-06-18 23:41 UTC, VelvetThePanda commented on DSharpPlus/Formatter.cs
> +        public static string TimeStamp(TimeSpan time, TimestampFormat format = TimestampFormat.RelativeTime)
what?

2021-06-18 23:41 UTC, VelvetThePanda commented on DSharpPlus/Formatter.cs
> +        public static string TimeStamp(TimeSpan time, TimestampFormat format = TimestampFormat.RelativeTime)
oh, sed

2021-06-18 23:43 UTC, VelvetThePanda commented on DSharpPlus/Enums/TimestampFormat.cs
> +    public enum TimestampFormat
![](https://cdn.velvetthepanda.dev/g1gim.png)

2021-06-18 23:46 UTC, Emzi0767 commented on DSharpPlus/Formatter.cs
> +        public static string TimeStamp(TimeSpan time, TimestampFormat format = TimestampFormat.RelativeTime)
Yes, also I forgot

2021-06-18 23:46 UTC, Emzi0767 requested changes
This is what I forgot

2021-06-19 00:00 UTC, VelvetThePanda commented
@Emzi0767 should be good now

2021-06-19 00:01 UTC, Emzi0767 approved these changes

2021-06-19 00:02 UTC, merged