Add support for new application command option types
DSharpPlus/DSharpPlus pull request #997
Opened 2021-07-18 13:40 UTC by IDoEverything

# Summary
Adds support for the `Mentionable` and `Number` application command option types.

# Details
Mentionable can be a user or a role, and apparently you're supposed to check which one it is from `Resolved`. Number allows for float/double values.

2021-07-18 14:18 UTC, Lulalaby approved these changes

2021-07-18 15:51 UTC, Kiritsu requested changes

2021-07-18 15:51 UTC, Kiritsu commented on DSharpPlus/Enums/Interaction/ApplicationCommandOptionType.cs
> +        /// Whether this paramter is a double.
parameter*

2021-07-18 16:24 UTC, Kiritsu approved these changes

2021-07-18 16:58 UTC, Neuheit commented
Will be merged when https://github.com/discord/discord-api-docs/pull/3455 is merged.

2021-07-26 18:59 UTC, IDoEverything commented
It's been merged

2021-07-26 19:41 UTC, Lulalaby commented
yes. @Neuheit 

@IDoEverything Atm I'm implementing this into slashcommands, but I've a few problems.
I'll make a pr if mine works.

2021-07-26 20:12 UTC, Lulalaby commented
@IDoEverything any idea?

Value: 0.2
Slash/Error: Input string was not in a correct format. | CN: volume | IID: 869308250892402709

DiscordInteractionDataOption
```csharp
        /// <summary>
        /// Gets the value of this interaction parameter.
        /// <para>This can be cast to a <see langword="long"/>, <see langword="bool"></see>, <see langword="string"></see>, <see langword="double"></see> or <see langword="ulong"/> depending on the <see cref="Type"/></para>
        /// </summary>
        [JsonIgnore]
        public object Value
        {
            get
            {
                Console.WriteLine("Value: " + this._value);
                return this.Type switch
                {
                    ApplicationCommandOptionType.Boolean => bool.Parse(this._value),
                    ApplicationCommandOptionType.Integer => long.Parse(this._value),
                    ApplicationCommandOptionType.String => this._value,
                    ApplicationCommandOptionType.Channel => ulong.Parse(this._value),
                    ApplicationCommandOptionType.User => ulong.Parse(this._value),
                    ApplicationCommandOptionType.Role => ulong.Parse(this._value),
                    ApplicationCommandOptionType.Mentionable => ulong.Parse(this._value),
                    ApplicationCommandOptionType.Number => double.Parse(this._value, NumberStyles.AllowDecimalPoint),
                    _ => this._value,
                };
            }
        }
```

But if I remove NumberStyles.AllowDecimalPoint
It resolves to double 2

----

Value: 0.2
Type: Nyaw.SlashCommands.Owner+VolumeChoiceProvider, Var: 2

This i get when i use the following code

DiscordInteractionDataOption
```csharp
        /// <summary>
        /// Gets the value of this interaction parameter.
        /// <para>This can be cast to a <see langword="long"/>, <see langword="bool"></see>, <see langword="string"></see>, <see langword="double"></see> or <see langword="ulong"/> depending on the <see cref="Type"/></para>
        /// </summary>
        [JsonIgnore]
        public object Value
        {
            get
            {
                Console.WriteLine("Value: " + this._value);
                return this.Type switch
                {
                    ApplicationCommandOptionType.Boolean => bool.Parse(this._value),
                    ApplicationCommandOptionType.Integer => long.Parse(this._value),
                    ApplicationCommandOptionType.String => this._value,
                    ApplicationCommandOptionType.Channel => ulong.Parse(this._value),
                    ApplicationCommandOptionType.User => ulong.Parse(this._value),
                    ApplicationCommandOptionType.Role => ulong.Parse(this._value),
                    ApplicationCommandOptionType.Mentionable => ulong.Parse(this._value),
                    ApplicationCommandOptionType.Number => Convert.ToDouble(this._value),
                    _ => this._value,
                };
            }
        }
```

```csharp

        [SlashCommand("volume", "Modifies the volume")]
        public static async Task ModifyVolumeAsync(InteractionContext ctx, [ChoiceProvider(typeof(VolumeChoiceProvider))][Option("volume", "Volume")] double volume)
        {
            Console.WriteLine($"Type: {typeof(VolumeChoiceProvider)}, Var: {volume}");
            await ctx.CreateResponseAsync(InteractionResponseType.DeferredChannelMessageWithSource, new DiscordInteractionResponseBuilder().WithContent("Changing Volume"));
            VoiceNextExtension vnext = ctx.Client.GetVoiceNext();
            VoiceNextConnection vnc = vnext.GetConnection(ctx.Guild);
            if (vnc == null)
                return;
            VoiceTransmitSink ts = vnc.GetTransmitSink();
            //ts.VolumeModifier = volume;
            await ctx.EditResponseAsync(new DiscordWebhookBuilder().WithContent($"Set volume to {ts.VolumeModifier}"));
        }
```

till `Console.WriteLine("Value: " + this._value);` it's correct.
after that, it converts wrong

2021-07-27 02:52 UTC, IDoEverything commented
![image](https://user-images.githubusercontent.com/65034167/127087473-d498b6a1-ac49-4c8e-9676-19841db269d4.png)
works for me

2021-07-27 03:02 UTC, Lulalaby commented
crazy

2021-07-27 05:46 UTC, Neuheit approved these changes

2021-07-27 05:46 UTC, merged